# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'download.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 397)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.download_list = QtWidgets.QListView(self.centralwidget)
        self.download_list.setObjectName("download_list")
        self.gridLayout.addWidget(self.download_list, 3, 0, 1, 1)
        self.download_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.download_button.setFont(font)
        self.download_button.setObjectName("download_button")
        self.gridLayout.addWidget(self.download_button, 1, 0, 1, 1)
        self.url = QtWidgets.QLineEdit(self.centralwidget)
        self.url.setObjectName("url")
        self.gridLayout.addWidget(self.url, 0, 0, 1, 1)
        self.download_list_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.download_list_label.setFont(font)
        self.download_list_label.setObjectName("download_list_label")
        self.gridLayout.addWidget(self.download_list_label, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python YouTube Video Downloader 影片下載器"))
        self.download_button.setText(_translate("MainWindow", "download"))
        self.download_list_label.setText(_translate("MainWindow", "download list"))
